- name: ensure epel repo installed
  copy: src=epel.repo dest=/etc/yum.repos.d/epel.repo

- name: ensure epel gpg key installed
  copy: src=RPM-GPG-KEY-EPEL-6 dest=/etc/pki/rpm-gpg

- name: install rpms for building couchdb
  yum: name={{ item }}
  with_items:
    - libicu-devel
    - openssl-devel
    - curl-devel
    - make
    - gcc
    - gcc-c++
    - erlang
    - js-devel
    - libtool
    - which

- stat: path=/usr/local/bin/couchdb
  register: couch_bin

- name: get couchdb tar
  get_url: url=http://download.nextag.com/apache/couchdb/source/1.6.1/apache-couchdb-1.6.1.tar.gz dest={{ root_dir }}/couchdb.tar.gz

- name: unzip couchdb
  shell: tar xvfz {{ root_dir }}/couchdb.tar.gz chdir={{ root_dir }}
  when: not couch_bin.stat.exists

- name: create couch user
  user: name=couchdb createhome=no


- name: configure
  shell: '{{ root_dir}}/apache-couchdb-1.6.1/configure --with-erlang=/usr/lib64/erlang/usr/include/'
  register: configure_result
  when: not couch_bin.stat.exists
  failed_when: configure_result.stderr and 'directory already configured' not in configure_result.stderr
  changed_when: not configure_result.stderr or 'directory already configured' not in configure_result.stderr
  sudo_user: couchdb

- name: make couch
  shell: 'make chdir={{ root_dir}}/apache-couchdb-1.6.1/'
  when: not couch_bin.stat.exists
  sudo_user: couchdb

- name: install couch
  shell: 'make install chdir={{ root_dir}}/apache-couchdb-1.6.1/'
  when: not couch_bin.stat.exists

- name: add service to init.d
  file: path=/etc/init.d/couchdb state=link src=/usr/local/etc/rc.d/couchdb

- name: get couchdb password
  shell: node -e "console.log(require('{{ kratos_dir }}/lib/config.js').COUCH_PWD)"
  register: couch_pwd
  changed_when: False

- name: template couch ini file
  template: src=local.ini.j2 dest=/usr/local/etc/couchdb/local.ini owner=couchdb
  notify: restart couchdb

- name: start couchdb
  service: name=couchdb enabled=yes state=started

- name: upgrade any design documents
  shell: icake -t {{ item }} sync_design_docs chdir={{ kratos_dir }}
  with_items:
    - _users
    - org
