- hosts:
    - production
  roles:
    - role: load_repos
      sudo: yes
- hosts:
    - vagrant
    - production
  roles:
    - role: django
      sudo: yes
    - role: node
      sudo: yes
    - role: couch
      sudo: yes
