- hosts:
    - production
  gather_facts: no
  roles:
    - role: load_repos
      sudo: yes
- hosts:
    - vagrant
    - production
  gather_facts: no
  vars:
    kratos_port: 5000
    moirai_port: 5001
    django_port: 8000
  roles:
    - role: django
      sudo: yes
    - role: node
      sudo: yes
    - role: couch
      sudo: yes
    - role: nginx
      sudo: yes
    - role: supervisord
      sudo: yes
